using ApiFake1.Model;
using Microsoft.Extensions.Hosting;
using System;
using System.Diagnostics;
using System.Net;

namespace ApiFake1.Enumerables
{

    public static class Tipologia
    {
        public static readonly KeyValueModel<string,string> Tp001 = new KeyValueModel<string,string>{ Key = "10101",  Value = "Conexão" };
        public static readonly KeyValueModel<string,string> Tp002 = new KeyValueModel<string,string>{ Key = "10102",  Value = "Cadastro / Contratos" };
        public static readonly KeyValueModel<string,string> Tp003 = new KeyValueModel<string,string>{ Key = "10103",  Value = "Benefícios Tarifários" };
        public static readonly KeyValueModel<string,string> Tp004 = new KeyValueModel<string,string>{ Key = "10104",  Value = "Medição / Equipamentos de Medição" };
        public static readonly KeyValueModel<string,string> Tp005 = new KeyValueModel<string,string>{ Key = "10105", Value = "Leitura" };
        public static readonly KeyValueModel<string,string> Tp006 = new KeyValueModel<string,string>{ Key = "10106",  Value = "Tarifas / Fatura / Faturamento / Cobrança" };
        public static readonly KeyValueModel<string,string> Tp007 = new KeyValueModel<string,string>{ Key = "10107",  Value = "Serviços Cobráveis" };
        public static readonly KeyValueModel<string,string> Tp008 = new KeyValueModel<string,string>{ Key = "10108",  Value = "Pagamento" };
        public static readonly KeyValueModel<string,string> Tp009 = new KeyValueModel<string,string>{ Key = "10109",  Value = "Suspensão do Fornecimento" };
        public static readonly KeyValueModel<string,string> Tp010 = new KeyValueModel<string,string>{ Key = "10110",  Value = "Procedimento Irregular" };
        public static readonly KeyValueModel<string,string> Tp011 = new KeyValueModel<string,string>{ Key = "10111",  Value = "Atendimento / Estrutura de Atendimento" };
        public static readonly KeyValueModel<string,string> Tp012 = new KeyValueModel<string,string>{ Key = "10112",  Value = "Qualidade da Prestação do Serviço" };
        public static readonly KeyValueModel<string,string> Tp013 = new KeyValueModel<string,string>{ Key = "10113",  Value = "Ressarcimento de Danos Elétricos" };
        public static readonly KeyValueModel<string,string> Tp014 = new KeyValueModel<string,string>{ Key = "10114",  Value = "Rede / Manutenção" };
        public static readonly KeyValueModel<string,string> Tp015 = new KeyValueModel<string,string>{ Key = "10115",  Value = "Geração Distribuída" };
        public static readonly KeyValueModel<string,string> Tp016 = new KeyValueModel<string,string>{ Key = "10116",  Value = "Prazos / acompanhamento de solicitação" };
        public static readonly KeyValueModel<string,string> Tp017 = new KeyValueModel<string,string>{ Key = "10117",  Value = "Instalação Interna" };
        public static readonly KeyValueModel<string,string> Tp018 = new KeyValueModel<string,string>{ Key = "10118",  Value = "Iluminação Pública" };
        public static readonly KeyValueModel<string,string> Tp020 = new KeyValueModel<string,string>{ Key = "10119",  Value = "Legislação do Setor Elétrico ou correlata" };
        public static readonly KeyValueModel<string,string> Tp021 = new KeyValueModel<string,string>{ Key = "10120",  Value = "Normas e Padrões Técnicos da distribuidora" };
        public static readonly KeyValueModel<string,string> Tp022 = new KeyValueModel<string,string>{ Key = "10121",  Value = "Eficiência Energética / Racionalização do consumo" };
        public static readonly KeyValueModel<string,string> Tp023 = new KeyValueModel<string,string>{ Key = "10122",  Value = "Caminho do entendimento(orientação para contato em outro nível)" };
        public static readonly KeyValueModel<string,string> Tp024 = new KeyValueModel<string,string>{ Key = "10199",  Value = "Outros " };
        public static readonly KeyValueModel<string,string> Tp025 = new KeyValueModel<string,string>{ Key = "1020101",  Value = "Solicitação não atendida ou atrasada" };
        public static readonly KeyValueModel<string,string> Tp026 = new KeyValueModel<string,string>{ Key = "1020102",  Value = "Orçamento - Participação Financeira / Universalização" };
        public static readonly KeyValueModel<string,string> Tp027 = new KeyValueModel<string,string>{ Key = "1020103",  Value = "Restituição de antecipação" };
        public static readonly KeyValueModel<string,string> Tp028 = new KeyValueModel<string,string>{ Key = "1020104",  Value = "Prazos(ligação com obras)" };
        public static readonly KeyValueModel<string,string> Tp029 = new KeyValueModel<string,string>{ Key = "1020105",  Value = "Prazos(ligação sem obras)" };
        public static readonly KeyValueModel<string,string> Tp030 = new KeyValueModel<string,string>{ Key = "1020199",  Value = "Outros" };
        public static readonly KeyValueModel<string,string> Tp031 = new KeyValueModel<string,string>{ Key = "1020201",  Value = "Cadastro" };
        public static readonly KeyValueModel<string,string> Tp032 = new KeyValueModel<string,string>{ Key = "1020202", Value="Uso não autorizado de dados cadastrais" };
        public static readonly KeyValueModel<string,string> Tp033 = new KeyValueModel<string,string>{ Key = "1020203", Value="Contratos / Encerramento contratual" };
        public static readonly KeyValueModel<string,string> Tp034 = new KeyValueModel<string,string>{ Key = "1020204", Value="Troca de titularidade" };
        public static readonly KeyValueModel<string,string> Tp035 = new KeyValueModel<string,string>{ Key = "1020299", Value="Outros  " };
        public static readonly KeyValueModel<string,string> Tp036 = new KeyValueModel<string,string>{ Key = "1020301", Value="Ausência do medidor/sistema de medição" };
        public static readonly KeyValueModel<string,string> Tp037 = new KeyValueModel<string,string>{ Key = "1020302", Value="Avaria/Defeito medidor/sistema de medição" };
        public static readonly KeyValueModel<string,string> Tp038 = new KeyValueModel<string,string>{ Key = "1020303", Value="Lacre   " };
        public static readonly KeyValueModel<string, string> Tp039 = new KeyValueModel<string, string> { Key = "1020399", Value = "Outros  " };
        public static readonly KeyValueModel<string, string> Tp040 = new KeyValueModel<string, string> { Key = "1020401", Value = "Impedimento de acesso" };
        public static readonly KeyValueModel<string, string> Tp041 = new KeyValueModel<string, string> { Key = "1020402", Value = "Erro de leitura" };
        public static readonly KeyValueModel<string, string> Tp042 = new KeyValueModel<string, string> { Key = "1020403", Value = "Variação de consumo" };
        public static readonly KeyValueModel<string, string> Tp043 = new KeyValueModel<string, string> { Key = "1020404", Value = "Demais grandezas faturadas" };
        public static readonly KeyValueModel<string, string> Tp044 = new KeyValueModel<string, string> { Key = "1020405", Value = "Tarifas aplicadas" };
        public static readonly KeyValueModel<string, string> Tp045 = new KeyValueModel<string, string> { Key = "1020406", Value = "Classificação / Subsídios tarifários" };
        public static readonly KeyValueModel<string, string> Tp046 = new KeyValueModel<string, string> { Key = "1020407", Value = "Faturamento por estimativa / média" };
        public static readonly KeyValueModel<string, string> Tp047 = new KeyValueModel<string, string> { Key = "1020408", Value = "Faturamento pelo custo de disponibilidade" };
        public static readonly KeyValueModel<string, string> Tp048 = new KeyValueModel<string, string> { Key = "1020409", Value = "Compensação / Devolução não realizada / incorreta" };
        public static readonly KeyValueModel<string, string> Tp049 = new KeyValueModel<string, string> { Key = "1020410", Value = "Bandeiras Tarifárias" };
        public static readonly KeyValueModel<string, string> Tp050 = new KeyValueModel<string, string> { Key = "1020411", Value = "Tributos" };
        public static readonly KeyValueModel<string, string> Tp051 = new KeyValueModel<string, string> { Key = "1020412", Value = "Contribuição para o Custeio dos Serviços de Iluminação Pública - COSIP" };
        public static readonly KeyValueModel<string, string> Tp052 = new KeyValueModel<string, string> { Key = "1020413", Value = "Apresentação / Entrega da fatura" };
        public static readonly KeyValueModel<string, string> Tp053 = new KeyValueModel<string, string> { Key = "1020414", Value = "Qualidade da impressão da fatura" };
        public static readonly KeyValueModel<string, string> Tp054 = new KeyValueModel<string, string> { Key = "1020499", Value = "Outros  " };
        public static readonly KeyValueModel<string, string> Tp055 = new KeyValueModel<string, string> { Key = "1020501", Value = "Acréscimos moratórios - Multas e juros" };
        public static readonly KeyValueModel<string, string> Tp056 = new KeyValueModel<string, string> { Key = "1020502", Value = "Cobranças de períodos anteriores" };
        public static readonly KeyValueModel<string, string> Tp057 = new KeyValueModel<string, string> { Key = "1020503", Value = "Parcelamento de débito" };
        public static readonly KeyValueModel<string, string> Tp058 = new KeyValueModel<string, string> { Key = "1020504", Value = "Serviços cobráveis" };
        public static readonly KeyValueModel<string, string> Tp059 = new KeyValueModel<string, string> { Key = "1020505", Value = "Atividades acessórias" };
        public static readonly KeyValueModel<string, string> Tp060 = new KeyValueModel<string, string> { Key = "1020599", Value = "Outros  " };
        public static readonly KeyValueModel<string, string> Tp061 = new KeyValueModel<string, string> { Key = "1020601", Value = "Fatura paga e não baixada" };
        public static readonly KeyValueModel<string, string> Tp062 = new KeyValueModel<string, string> { Key = "1020602", Value = "Indisponibilidade / Inexistência de posto de arrecadação no Município" };
        public static readonly KeyValueModel<string, string> Tp063 = new KeyValueModel<string, string> { Key = "1020603", Value = "Suspensão indevida" };
        public static readonly KeyValueModel<string, string> Tp064 = new KeyValueModel<string, string> { Key = "1020604", Value = "Religação não realizada / fora do prazo" };
        public static readonly KeyValueModel<string, string> Tp065 = new KeyValueModel<string, string> { Key = "1020605", Value = "Inscrição em Cadastro de Negativação" };
        public static readonly KeyValueModel<string, string> Tp066 = new KeyValueModel<string, string> { Key = "1020606", Value = "Atuação de empresa de cobrança" };
        public static readonly KeyValueModel<string, string> Tp067 = new KeyValueModel<string, string> { Key = "1020699", Value = "Outros  " };
        public static readonly KeyValueModel<string, string> Tp068 = new KeyValueModel<string, string> { Key = "1020701", Value = "Valores cobrados" };
        public static readonly KeyValueModel<string, string> Tp069 = new KeyValueModel<string, string> { Key = "1020702", Value = "Deficiência na caracterização da irregularidade" };
        //public static readonly KeyValueModel<string, string> Tp009 = new KeyValueModel<string, string> { Key = "1020703", Value = "Não recebimento do TOI - Termo de Ocorrência e Inspeção" };
        //public static readonly KeyValueModel<string, string> Tp009 = new KeyValueModel<string, string> { Key = "1020704", Value = "Responsabilidade sobre a Irregularidade" };
        //public static readonly KeyValueModel<string, string> Tp009 = new KeyValueModel<string, string> { Key = "1020705", Value = "Cobrança decorrente de religação à revelia" };
        //public static readonly KeyValueModel<string, string> Tp009 = new KeyValueModel<string, string> { Key = "1020799", Value = "Outros  " };
        //public static readonly KeyValueModel<string, string> Tp009 = new KeyValueModel<string, string> { Key = "1020801", Value = "Conduta de empregado ou prestador de serviço" };
        //public static readonly KeyValueModel<string, string> Tp009 = new KeyValueModel<string, string> { Key = "1020802", Value = "Atendimento Presencial / Falta de agência / posto de atendimento" };
        //public static readonly KeyValueModel<string, string> Tp009 = new KeyValueModel<string, string> { Key = "1020803", Value = "Atendimento Telefônico" };
        //public static readonly KeyValueModel<string, string> Tp009 = new KeyValueModel<string, string> { Key = "1020804", Value = "Atendimento pela Internet" };
        //public static readonly KeyValueModel<string, string> Tp009 = new KeyValueModel<string, string> { Key = "1020805", Value = "Demais canais de acesso" };
        //public static readonly KeyValueModel<string, string> Tp001 = new KeyValueModel<string, string> { Key = "1020899", Value = "Outros  " };
        //public static readonly KeyValueModel<string, string> Tp001 = new KeyValueModel<string, string> { Key = "1020901", Value = "Interrupção no Fornecimento - Falta de energia" };
        //public static readonly KeyValueModel<string, string> Tp001 = new KeyValueModel<string, string> { Key = "1020902", Value = "Interrupção Frequente do Fornecimento" };
        //public static readonly KeyValueModel<string, string> Tp001 = new KeyValueModel<string, string> { Key = "1020903", Value = "Interrupção Programada" };
        //public static readonly KeyValueModel<string, string> Tp001 = new KeyValueModel<string, string> { Key = "1020904", Value = "Tensão de Fornecimento" };
        //public static readonly KeyValueModel<string, string> Tp001 = new KeyValueModel<string, string> { Key = "1020999", Value = "Outros  " };
        //public static readonly KeyValueModel<string, string> Tp001 = new KeyValueModel<string, string> { Key = "1021001", Value = "Danos em equipamentos" };
        //public static readonly KeyValueModel<string, string> Tp001 = new KeyValueModel<string, string> { Key = "1021002", Value = "Vistoria dos Equipamentos" };
        //public static readonly KeyValueModel<string, string> Tp001 = new KeyValueModel<string, string> { Key = "1021003", Value = "Laudo/orçamento" };
        //public static readonly KeyValueModel<string, string> Tp001 = new KeyValueModel<string, string> { Key = "1021004", Value = "Ressarcimento inferior ao devido" };
        //public static readonly KeyValueModel<string, string> Tp001 = new KeyValueModel<string, string> { Key = "1021005", Value = "Indeferimento total / parcial" };
        //public static readonly KeyValueModel<string, string> Tp001 = new KeyValueModel<string, string> { Key = "1021099", Value = "Outros  " };
        //public static readonly KeyValueModel<string, string> Tp001 = new KeyValueModel<string, string> { Key = "1021201", Value = "Cabo partido" };
        //public static readonly KeyValueModel<string, string> Tp001 = new KeyValueModel<string, string> { Key = "1021202", Value = "Poste   " };
        //public static readonly KeyValueModel<string, string> Tp001 = new KeyValueModel<string, string> { Key = "1021203", Value = "Transformador" };
        //public static readonly KeyValueModel<string, string> Tp001 = new KeyValueModel<string, string> { Key = "1021204", Value = "Objeto na rede" };
        //public static readonly KeyValueModel<string, string> Tp001 = new KeyValueModel<string, string> { Key = "1021205", Value = "Poda de árvore" };
        //public static readonly KeyValueModel<string, string> Tp001 = new KeyValueModel<string, string> { Key = "1021206", Value = "Entulhos / Galhos de árvores não recolhidos" };
        //public static readonly KeyValueModel<string, string> Tp001 = new KeyValueModel<string, string> { Key = "1021299", Value = "Outros  " };
        //public static readonly KeyValueModel<string, string> Tp001 = new KeyValueModel<string, string> { Key = "1021301", Value = "Conexão " };
        //public static readonly KeyValueModel<string, string> Tp001 = new KeyValueModel<string, string> { Key = "1021302", Value = "Faturamento" };
        //public static readonly KeyValueModel<string, string> Tp001 = new KeyValueModel<string, string> { Key = "1021303", Value = "Variação de Consumo" };
        //public static readonly KeyValueModel<string, string> Tp001 = new KeyValueModel<string, string> { Key = "1021304", Value = "Apresentação / Entrega de Fatura" };
        //public static readonly KeyValueModel<string, string> Tp001 = new KeyValueModel<string, string> { Key = "1021399", Value = "Outros  " };
        //public static readonly KeyValueModel<string, string> Tp001 = new KeyValueModel<string, string> { Key = "10214", Value = "Pazos(não previstos nas tipologias anteriores)" };
        //public static readonly KeyValueModel<string, string> Tp001 = new KeyValueModel<string, string> { Key = "10215", Value = "Instalações internas" };
        //public static readonly KeyValueModel<string, string> Tp001 = new KeyValueModel<string, string> { Key = "10216", Value = "Iluminação Pública" };
        //public static readonly KeyValueModel<string, string> Tp001 = new KeyValueModel<string, string> { Key = "10217", Value = "Outros    " };
        //public static readonly KeyValueModel<string, string> Tp001 = new KeyValueModel<string, string> { Key = "10401", Value = "Ligação Clandestina" };
        //public static readonly KeyValueModel<string, string> Tp001 = new KeyValueModel<string, string> { Key = "10402", Value = "Fraude/Desvio de Energia Elétrica" };
        //public static readonly KeyValueModel<string, string> Tp001 = new KeyValueModel<string, string> { Key = "10403", Value = "Contra empregado ou prestador de serviço da distribuidora" };
        //public static readonly KeyValueModel<string, string> Tp001 = new KeyValueModel<string, string> { Key = "10404", Value = "Danos Ambientais" };
        //public static readonly KeyValueModel<string, string> Tp001 = new KeyValueModel<string, string> { Key = "10405", Value = "Furtos de cabos e fiações elétricas" };
        //public static readonly KeyValueModel<string, string> Tp001 = new KeyValueModel<string, string> { Key = "10406", Value = "Outros    " };
        //public static readonly KeyValueModel<string, string> Tp001 = new KeyValueModel<string, string> { Key = "105", Value = "ELOGIO      " };
        //public static readonly KeyValueModel<string, string> Tp001 = new KeyValueModel<string, string> { Key = "106", Value = "SUGESTÃO    " };
        //public static readonly KeyValueModel<string, string> Tp001 = new KeyValueModel<string, string> { Key = "107", Value = "CANCELAMENTO DE SERVIÇOS" };"
        public static IEnumerable<KeyValueModel<string,string>> List
        {
            get
            {
                yield return Tp001;
                yield return Tp002;
                yield return Tp003;
                yield return Tp004;
                yield return Tp005;
                yield return Tp006;
                yield return Tp007;
                yield return Tp008;
                yield return Tp009;
                yield return Tp010;
                yield return Tp011;
                yield return Tp012;
                yield return Tp013;
                yield return Tp014;
                yield return Tp015;
                yield return Tp016;
                yield return Tp017;
                yield return Tp018;
                yield return Tp020;
                yield return Tp021;
                yield return Tp022;
                yield return Tp023;
                yield return Tp024;
                yield return Tp025;
                yield return Tp026;
                yield return Tp027;
                yield return Tp028;
                yield return Tp029;
                yield return Tp030;
                yield return Tp031;
                yield return Tp032;
                yield return Tp033;
                yield return Tp034;
                yield return Tp035;
                yield return Tp036;
                yield return Tp037;
                yield return Tp038;
                yield return Tp039;
                yield return Tp040;
                yield return Tp041;
                yield return Tp042;
                yield return Tp043;
                yield return Tp044;
                yield return Tp045;
                yield return Tp046;
                yield return Tp047;
                yield return Tp048;
                yield return Tp049;
                yield return Tp050;
                yield return Tp051;
                yield return Tp052;
                yield return Tp053;
                yield return Tp054;
                yield return Tp055;
                yield return Tp056;
                yield return Tp057;
                yield return Tp058;
                yield return Tp059;
                yield return Tp060;
                yield return Tp061;
                yield return Tp062;
                yield return Tp063;
                yield return Tp064;
                yield return Tp065;
                yield return Tp066;
                yield return Tp067;
                yield return Tp068;
                yield return Tp069;
            }
        }
    }
}
